server:
  port: 9090
  servlet.context-path: /demo
  undertow.max-http-post-size: 0

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.web.FilterChainProxy: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.security: DEBUG
    org.springframework.boot.autoconfigure: INFO

spring:
  application.name: demo
  main.allow-bean-definition-overriding: true
  thymeleaf:
    cache: false
    check-template-location: true
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    template-resolver-order: 1
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  jms.listener.auto-startup: false
  jackson.default-property-inclusion: non_absent
#    database: mysql
#  datasource:
#    url: jdbc:mysql://localhost:3306/myDB
#    username: root
#    password: 123456

app.datasource.realdb.url: jdbc:mysql://52.197.35.82/b_monster?useSSL=false
app.datasource.realdb.username: b_monster_pl
app.datasource.realdb.password: h6L7_xqc

app.datasource.sakila.url: jdbc:mysql://localhost:3306/sakila
app.datasource.sakila.username: root
app.datasource.sakila.password: 123456

app.datasource.employee.url: jdbc:mysql://localhost:3306/employees
app.datasource.employee.username: root
app.datasource.employee.password: 123456

#keycloak:
#  enabled: true
#  auth-server-url: http://localhost:8080/auth
#  realm: demo-realm
#  resource: demo-client
#  ssl-required: none
#  credentials.secret: 12b92093-4336-426d-8267-f89b31d347f7
#  bearer-only: true
#  principal-attribute: preferred_username
